import { ISetting, SettingType } from '@rocket.chat/apps-engine/definition/settings';

export enum RssSetting {
    DefaultPollIntervalMinutes = 'rss_default_poll_interval_minutes',
    DefaultTargetChannel = 'rss_default_target_channel',
    RequestTimeoutMs = 'rss_request_timeout_ms',
    UserAgent = 'rss_user_agent',
    DryRunMode = 'rss_dry_run_mode',
}

export const settings: Array<ISetting> = [
    {
        id: RssSetting.DefaultPollIntervalMinutes,
        section: 'RSS General',
        public: false,
        type: SettingType.NUMBER,
        value: 15,
        packageValue: 15,
        hidden: false,
        i18nLabel: 'Default poll interval in minutes',
        i18nDescription: 'Used when a subscription does not provide its own polling interval.',
        required: true,
    },
    {
        id: RssSetting.DefaultTargetChannel,
        section: 'RSS General',
        public: false,
        type: SettingType.STRING,
        value: '',
        packageValue: '',
        hidden: false,
        i18nLabel: 'Default target channel',
        i18nDescription: 'Optional fallback channel for subscriptions created outside a target room. Accepts #channel or channel name.',
        required: false,
    },
    {
        id: RssSetting.RequestTimeoutMs,
        section: 'RSS HTTP',
        public: false,
        type: SettingType.NUMBER,
        value: 10000,
        packageValue: 10000,
        hidden: false,
        i18nLabel: 'HTTP request timeout in milliseconds',
        i18nDescription: 'Maximum time to wait for a feed response before the request is treated as failed.',
        required: true,
    },
    {
        id: RssSetting.UserAgent,
        section: 'RSS HTTP',
        public: false,
        type: SettingType.STRING,
        value: 'RocketChatRSS/0.2.0',
        packageValue: 'RocketChatRSS/0.2.0',
        hidden: false,
        i18nLabel: 'HTTP user agent',
        i18nDescription: 'User-Agent header sent when fetching RSS and Atom feeds.',
        required: true,
    },
    {
        id: RssSetting.DryRunMode,
        section: 'RSS Safety',
        public: false,
        type: SettingType.BOOLEAN,
        value: true,
        packageValue: true,
        hidden: false,
        i18nLabel: 'Dry-run mode',
        i18nDescription: 'When enabled, feeds are fetched and tracked but new items are not posted into rooms.',
        required: false,
    },
];
