import { ISetting, SettingType } from '@rocket.chat/apps-engine/definition/settings';

export enum RssSetting {
    DefaultPollIntervalMinutes = 'rss_default_poll_interval_minutes',
    DefaultTargetChannel = 'rss_default_target_channel',
    RequestTimeoutMs = 'rss_request_timeout_ms',
    UserAgent = 'rss_user_agent',
    DryRunMode = 'rss_dry_run_mode',
}

export const settings: Array<ISetting> = [
    {
        id: RssSetting.DefaultPollIntervalMinutes,
        section: 'RSS_General',
        public: false,
        type: SettingType.NUMBER,
        value: 15,
        packageValue: 15,
        hidden: false,
        i18nLabel: 'RSS_DefaultPollIntervalMinutes',
        i18nDescription: 'RSS_DefaultPollIntervalMinutes_Description',
        required: true,
    },
    {
        id: RssSetting.DefaultTargetChannel,
        section: 'RSS_General',
        public: false,
        type: SettingType.STRING,
        value: '',
        packageValue: '',
        hidden: false,
        i18nLabel: 'RSS_DefaultTargetChannel',
        i18nDescription: 'RSS_DefaultTargetChannel_Description',
        required: false,
    },
    {
        id: RssSetting.RequestTimeoutMs,
        section: 'RSS_HTTP',
        public: false,
        type: SettingType.NUMBER,
        value: 10000,
        packageValue: 10000,
        hidden: false,
        i18nLabel: 'RSS_RequestTimeoutMs',
        i18nDescription: 'RSS_RequestTimeoutMs_Description',
        required: true,
    },
    {
        id: RssSetting.UserAgent,
        section: 'RSS_HTTP',
        public: false,
        type: SettingType.STRING,
        value: 'RocketChatRSS/0.1.0',
        packageValue: 'RocketChatRSS/0.1.0',
        hidden: false,
        i18nLabel: 'RSS_UserAgent',
        i18nDescription: 'RSS_UserAgent_Description',
        required: true,
    },
    {
        id: RssSetting.DryRunMode,
        section: 'RSS_Safety',
        public: false,
        type: SettingType.BOOLEAN,
        value: true,
        packageValue: true,
        hidden: false,
        i18nLabel: 'RSS_DryRunMode',
        i18nDescription: 'RSS_DryRunMode_Description',
        required: false,
    },
];
